package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/abhyuday404/prava-hack/internal/domain"
	"gopkg.in/yaml.v3"
)

var manifestNames = []string{"prava-deploy.yaml", ".prava-deploy.yaml", "ship.yaml"}

type Manifest struct {
	Version string  `yaml:"version" json:"version"`
	Project Project `yaml:"project" json:"project"`
	Deploy  Deploy  `yaml:"deploy" json:"deploy"`
	Budget  Budget  `yaml:"budget" json:"budget"`
	Policy  Policy  `yaml:"policy" json:"policy"`
}

type Project struct {
	Name         string               `yaml:"name" json:"name"`
	Kind         domain.ProjectKind   `yaml:"kind" json:"kind"`
	Runtime      string               `yaml:"runtime" json:"runtime"`
	Framework    string               `yaml:"framework" json:"framework"`
	Build        domain.BuildStrategy `yaml:"build" json:"build"`
	BuildCommand string               `yaml:"build_command" json:"build_command"`
	StartCommand string               `yaml:"start_command" json:"start_command"`
	OutputDir    string               `yaml:"output_dir" json:"output_dir"`
	Port         int                  `yaml:"port" json:"port"`
}

type Deploy struct {
	Provider string            `yaml:"provider" json:"provider"`
	Region   string            `yaml:"region" json:"region"`
	Config   map[string]string `yaml:"config" json:"config"`
}

type Budget struct {
	MonthlyMax string `yaml:"monthly_max" json:"monthly_max"`
	Currency   string `yaml:"currency" json:"currency"`
	Cadence    string `yaml:"cadence" json:"cadence"`
}

type Policy struct {
	RequireBudgetApproval bool     `yaml:"require_budget_approval" json:"require_budget_approval"`
	AllowedProviders      []string `yaml:"allowed_providers" json:"allowed_providers"`
	DeniedProviders       []string `yaml:"denied_providers" json:"denied_providers"`
	AllowProduction       bool     `yaml:"allow_production" json:"allow_production"`
}

func Defaults() Manifest {
	return Manifest{
		Version: domain.SchemaVersion,
		Budget:  Budget{Currency: "USD", Cadence: "monthly"},
		Policy:  Policy{RequireBudgetApproval: true},
	}
}

func Load(root string) (Manifest, string, error) {
	manifest := Defaults()
	for _, name := range manifestNames {
		path := filepath.Join(root, name)
		b, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return Manifest{}, "", fmt.Errorf("read manifest %s: %w", path, err)
		}
		if err := yaml.Unmarshal(b, &manifest); err != nil {
			return Manifest{}, "", fmt.Errorf("decode manifest %s: %w", path, err)
		}
		if manifest.Version == "" {
			manifest.Version = domain.SchemaVersion
		}
		if manifest.Version != domain.SchemaVersion {
			return Manifest{}, "", fmt.Errorf("unsupported manifest version %q", manifest.Version)
		}
		if manifest.Budget.Currency == "" {
			manifest.Budget.Currency = "USD"
		}
		if manifest.Budget.Cadence == "" {
			manifest.Budget.Cadence = "monthly"
		}
		return manifest, path, nil
	}
	return manifest, "", nil
}

func Apply(spec domain.ProjectSpec, manifest Manifest) domain.ProjectSpec {
	if manifest.Project.Name != "" {
		spec.Name = manifest.Project.Name
	}
	if manifest.Project.Kind != "" {
		spec.Kind = manifest.Project.Kind
	}
	if manifest.Project.Runtime != "" {
		spec.Runtime = manifest.Project.Runtime
	}
	if manifest.Project.Framework != "" {
		spec.Framework = manifest.Project.Framework
	}
	if manifest.Project.Build != "" {
		spec.Build = manifest.Project.Build
	}
	if manifest.Project.BuildCommand != "" {
		spec.BuildCommand = manifest.Project.BuildCommand
	}
	if manifest.Project.StartCommand != "" {
		spec.StartCommand = manifest.Project.StartCommand
	}
	if manifest.Project.OutputDir != "" {
		spec.OutputDir = manifest.Project.OutputDir
	}
	if manifest.Project.Port > 0 {
		spec.Port = manifest.Project.Port
	}
	return spec
}

func Render(spec domain.ProjectSpec) ([]byte, error) {
	m := Defaults()
	m.Project = Project{
		Name: spec.Name, Kind: spec.Kind, Runtime: spec.Runtime, Framework: spec.Framework,
		Build: spec.Build, BuildCommand: spec.BuildCommand, StartCommand: spec.StartCommand,
		OutputDir: spec.OutputDir, Port: spec.Port,
	}
	m.Deploy.Provider = "auto"
	m.Budget.MonthlyMax = "10.00"
	b, err := yaml.Marshal(m)
	if err != nil {
		return nil, err
	}
	header := "# Generated by prava-deploy. Review the budget and provider before deploying.\n"
	return append([]byte(header), b...), nil
}

func Validate(m Manifest) error {
	if m.Version != "" && m.Version != domain.SchemaVersion {
		return fmt.Errorf("version must be %q", domain.SchemaVersion)
	}
	if m.Budget.Currency != "" && len(strings.TrimSpace(m.Budget.Currency)) != 3 {
		return fmt.Errorf("budget.currency must be a three-letter ISO 4217 code")
	}
	if m.Budget.Cadence != "" && m.Budget.Cadence != "monthly" && m.Budget.Cadence != "one_time" {
		return fmt.Errorf("budget.cadence must be monthly or one_time")
	}
	for key := range m.Deploy.Config {
		lower := strings.ToLower(key)
		for _, fragment := range []string{"secret", "token", "password", "api_key", "apikey", "deploy_hook"} {
			if strings.Contains(lower, fragment) {
				return fmt.Errorf("deploy.config.%s may contain a secret; pass credentials through the provider's environment or native login instead", key)
			}
		}
	}
	return nil
}
